'use client';
import {useEffect,useState} from 'react';
import {Plus,Copy,RefreshCw,Search} from 'lucide-react';
import type {Machine} from '@/shared/types';
import type {PortView} from '@/shared/ports';
import {Empty,Modal} from './primitives';
type Draft={id?:string;ownerId:string;label:string;protocol:'tcp'|'udp';hostPort:number;targetPort:number};
export function PortsPanel({machines,action}:{machines:Machine[];action:(path:string,body?:unknown)=>Promise<any>}) {
  const [rows,setRows]=useState<PortView[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const [help,setHelp]=useState(false);
  const [draft,setDraft]=useState<Draft>(),[removing,setRemoving]=useState<PortView>(),[busy,setBusy]=useState(false);
  const refresh=async()=>{const r=await fetch('/api/network/mappings');const result=await r.json();if(!r.ok)throw new Error(result.error??'映射读取失败');setRows(result);};
  useEffect(()=>{let loading=false,active=true;const poll=async()=>{if(loading)return;loading=true;try{const r=await fetch('/api/network/mappings');const result=await r.json();if(!r.ok)throw new Error(result.error??'映射读取失败');if(active)setRows(result);}catch(e){if(active)setError((e as Error).message);}finally{loading=false;}};void poll();const t=setInterval(()=>void poll(),3000);return()=>{active=false;clearInterval(t);};},[]);
  const filtered=rows.filter(p=>(filter==='all'||p.ownerType===filter)&&`${p.ownerName} ${p.label} ${p.hostPort} ${p.targetPort}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="ports-panel">
    <div className="list-toolbar"><div className="filters">{[['all','全部'],['vm','虚拟机'],['docker','Docker']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="inline"><button className="icon-button" aria-label="刷新端口映射" onClick={()=>void refresh().catch(e=>setError(e.message))}><RefreshCw size={18}/></button><button className="button primary" disabled={busy||!machines.length} onClick={()=>{setError('');setDraft({ownerId:machines[0].id,label:'Web 服务',protocol:'tcp',hostPort:8080,targetPort:80});}}><Plus size={16}/>添加虚拟机映射</button></div></div>
    <div className="workspace-filter-bar"><label className="search"><Search size={15}/><input type="search" aria-label="搜索端口映射" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索资源、用途或端口…"/></label><span>{filtered.length} 条映射 · {rows.filter(p=>p.status==='running').length} 条所属资源运行中</span></div>
    {error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="saved" role="status">{notice}</p>}
    <section className="workspace-scroll ports-results" aria-label="端口映射列表" tabIndex={0}>{filtered.length?<div className="data-table-wrap"><table className="data-table port-table"><thead><tr><th>所属资源 / 用途</th><th>本机入口 → 目标端口</th><th>运行状态</th><th>操作</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.ownerName}</strong><small>{p.label} · {p.source==='ssh'?'自动 SSH':p.source==='docker'?'Docker':'NAT 自定义'}</small></td><td><code>{p.hostAddress}:{p.hostPort} → {p.targetPort}/{p.protocol.toUpperCase()}</code></td><td><span className={`status ${p.status==='running'?'running':'stopped'}`}><span/>{p.status==='running'?'资源运行中':p.status==='stopped'?'资源已停止':'状态待确认'}</span></td><td><div className="inline"><button className="icon-button" aria-label={`复制端口 ${p.hostPort}`} onClick={()=>void navigator.clipboard.writeText(`${p.hostAddress}:${p.hostPort}`).then(()=>setNotice('本机入口已复制')).catch(()=>setError('复制失败，请手动复制地址'))}><Copy size={16}/></button>{p.editable&&<><button className="text-button" disabled={busy||machines.find(m=>m.id===p.ownerId)?.state!=='stopped'} onClick={()=>setDraft({id:p.id,ownerId:p.ownerId,label:p.label,protocol:p.protocol,hostPort:p.hostPort,targetPort:p.targetPort})}>编辑</button><button className="text-button" disabled={busy} onClick={()=>setRemoving(p)}>删除</button></>}</div></td></tr>)}</tbody></table></div>:<Empty title="暂无匹配的端口映射" description="启动 Linux 虚拟机后会显示 SSH 入口。可以添加 Web、数据库等服务映射，Docker 发布端口也会汇总到这里。"/>}
    </section><footer className="workspace-foot"><span>本机入口 → 实例内端口</span><button className="text-button" onClick={()=>setHelp(true)}>映射说明</button></footer>
    {help&&<Modal title="端口映射说明" close={()=>setHelp(false)}><p className="field-help">NAT 映射默认仅本机可访问。运行状态表示所属实例或容器的状态，不代表目标服务已监听。SSH 端口由程序分配；Docker 端口在创建容器或 Compose 配置中管理。修改已有虚拟机映射前需先关机。</p></Modal>}
    {draft&&<Modal title={draft.id?'编辑端口映射':'添加端口映射'} close={()=>{if(!busy)setDraft(undefined);}}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const {id,...body}=draft;await action(id?`network/mappings/${id}/update`:'network/mappings',body);await refresh();setDraft(undefined);setNotice('映射已保存，实例重启后仍会保留');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
      <label>虚拟机<select aria-label="映射所属虚拟机" required disabled={!!draft.id} value={draft.ownerId} onChange={e=>setDraft({...draft,ownerId:e.target.value})}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
      <label>用途名称<input required maxLength={60} value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label>
      <div className="form-grid"><label>本机端口<input aria-label="本机端口" type="number" required min={1024} max={65535} value={draft.hostPort} onChange={e=>setDraft({...draft,hostPort:Number(e.target.value)})}/></label><label>实例内端口<input aria-label="实例内端口" type="number" required min={1} max={65535} value={draft.targetPort} onChange={e=>setDraft({...draft,targetPort:Number(e.target.value)})}/></label></div>
      <label>协议<select value={draft.protocol} onChange={e=>setDraft({...draft,protocol:e.target.value as 'tcp'|'udp'})}><option value="tcp">TCP</option><option value="udp">UDP</option></select></label><p className="notice">127.0.0.1:{draft.hostPort} → 实例端口 {draft.targetPort}。请同时确认实例里的服务已经启动。</p>
      {error&&<p className="form-error" role="alert">{error}</p>}<footer className="modal-foot"><button type="button" className="button secondary" onClick={()=>setDraft(undefined)} disabled={busy}>取消</button><button className="button primary" disabled={busy}>保存映射</button></footer>
    </form></Modal>}
    {removing&&<Modal title="删除端口映射" close={()=>setRemoving(undefined)}><p>删除 {removing.label}（{removing.hostPort} → {removing.targetPort}）。虚拟机和其中的数据会保留。</p><footer className="modal-foot"><button className="button secondary" onClick={()=>setRemoving(undefined)}>取消</button><button className="button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await action(`network/mappings/${removing.id}/delete`);setRemoving(undefined);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>确认删除</button></footer></Modal>}
  </section>;
}
