'use client';
import {useCallback,useEffect,useState} from 'react';
import {Plus,RefreshCw,History,Search,LoaderCircle,SlidersHorizontal} from 'lucide-react';
import type {DockerContainer,DockerSnapshot} from '@/shared/docker';
import type {FileListing,FilePickerKind} from '@/shared/file-picker';
import {useFilePicker} from '../file-picker';
import {Empty,Modal} from '../primitives';
import {ManagedEngine} from './managed-engine';
import {ResourceList} from './resource-list';

type Action=(path:string,body?:unknown)=>Promise<any>;
export function DockerPanel({action}:{action:Action}) {
  const [data,setData]=useState<DockerSnapshot>(),[error,setError]=useState(''),[context,setContext]=useState(''),[tab,setTab]=useState<'containers'|'images'|'projects'>('containers');
  const [form,setForm]=useState<'create'|'pull'|'project'>(),[image,setImage]=useState('nginx:alpine'),[projectPath,setProjectPath]=useState(''),[pending,setPending]=useState(false);
  const [logs,setLogs]=useState<{name:string;text:string}>(),[commandTarget,setCommandTarget]=useState<DockerContainer>(),[commandId,setCommandId]=useState('');
  const [removing,setRemoving]=useState<{name:string;path:string;description:string}>();
  const [history,setHistory]=useState(false),[connectionOpen,setConnectionOpen]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const [mode,setMode]=useState<'managed'|'external'>();
  const refresh=useCallback(async()=>{const response=await fetch('/api/docker');const value=await response.json();if(!response.ok)throw new Error(value.error??'Docker 读取失败');setData(value);},[]);
  useEffect(()=>{let live=true,loading=false;const poll=async()=>{if(loading)return;loading=true;try{await refresh();}catch(e){if(live)setError((e as Error).message);}finally{loading=false;}};void poll();const timer=setInterval(()=>void poll(),3000);return()=>{live=false;clearInterval(timer);};},[refresh]);
  const list=useCallback((request:{kind:FilePickerKind;path?:string})=>action('files/list',request) as Promise<FileListing>,[action]);
  const {pick,dialog:picker}=useFilePicker(list);
  const working=pending||!!data?.operations.some(o=>o.state==='running');
  const invoke=async(path:string,body:unknown={})=>{setPending(true);setError('');try{const result=await action(`docker/${path}`,body);await refresh();return result;}catch(e){setError((e as Error).message);throw e;}finally{setPending(false);}};
  const control=(c:DockerContainer,verb:string)=>void invoke(`containers/${c.id}/${verb}`).catch(()=>{});
  const recent=data?.operations??[];
  const execution=recent.find(o=>o.id===commandId);
  const selectedMode=mode??(data?.engine?.kind==='managed'||!data?.engine?'managed':'external');
  const showsResources=data?.engine&&(data.engine.kind==='managed'?'managed':'external')===selectedMode;
  const externalEngine=data?.engine?.kind!=='managed'?data?.engine:undefined;
  const externalContext=context||externalEngine?.context||data?.contexts.find(c=>c.current)?.name||data?.contexts[0]?.name||'';
  const activeOperation=recent.find(o=>o.state==='running');
  const switchMode=(value:'managed'|'external')=>{setMode(value);setQuery('');setFilter('all');};
  return <section className="docker-panel" aria-label="Docker 工作台">
    <header className="docker-command-bar"><div className="docker-title"><h1>Docker <span>容器</span></h1><p>运行服务，专注于你的项目。</p></div><div className="docker-global-actions"><div className="engine-modes" role="group" aria-label="Docker 引擎类型"><button aria-pressed={selectedMode==='managed'} className={selectedMode==='managed'?'selected':''} onClick={()=>switchMode('managed')}>DeskLab 内置</button><button aria-pressed={selectedMode==='external'} className={selectedMode==='external'?'selected':''} onClick={()=>switchMode('external')}>外部 Docker</button></div><button className="icon-button docker-history-button" aria-label="操作记录" title="操作记录" onClick={()=>setHistory(true)}><History size={18}/>{recent.some(o=>o.state==='running'||o.state==='failed')&&<i/>}</button><button className="icon-button" aria-label="刷新 Docker" title="刷新 Docker" disabled={pending} onClick={()=>void refresh().catch(e=>setError(e.message))}><RefreshCw size={17}/></button></div></header>
    {selectedMode==='managed'&&<ManagedEngine data={data?.managed} selected={data?.engine?.kind==='managed'} working={working} invoke={invoke}/>}
    {selectedMode==='external'&&<div className="docker-engine-strip"><span className={externalEngine?'online-dot':'offline-dot'}/><strong>{externalEngine?.context??'外部 Docker'}</strong><span className="engine-brief">{externalEngine?'已连接 · 外部 Linux 引擎':'连接这台电脑已有的 Docker 引擎'}</span><button className="button secondary compact" onClick={()=>setConnectionOpen(true)}><SlidersHorizontal size={15}/>{externalEngine?'连接设置':'连接引擎'}</button></div>}
    {connectionOpen&&<Modal title="连接外部 Docker 引擎" close={()=>setConnectionOpen(false)}><p className="field-help">选择这台电脑已有的 Docker 引擎。资源与内置引擎分开。</p><label>连接上下文<select aria-label="Docker 连接上下文" disabled={working} value={externalContext} onChange={e=>setContext(e.target.value)}>{!data?.contexts.length&&<option value="">未找到 Docker context</option>}{data?.contexts.map(c=><option key={c.name} value={c.name}>{c.name}{c.current?'（当前）':''}</option>)}</select></label>{!data?.contexts.length&&<p className="notice">请确认外部 Docker 已安装，然后关闭此窗口并刷新。</p>}<footer className="modal-foot"><button className="button secondary" onClick={()=>setConnectionOpen(false)}>取消</button><button className="button primary" disabled={working||!data?.available||!data.contexts.length} onClick={()=>void invoke('connect',{context:externalContext}).then(()=>setConnectionOpen(false)).catch(()=>{})}>连接引擎</button></footer>{error&&<p className="form-error" role="alert">{error}</p>}</Modal>}
    {(error||data?.error)&&<p className="alert error docker-alert" role="alert">{error||data?.error}</p>}
    {activeOperation&&<button className="docker-progress" onClick={()=>setHistory(true)}><LoaderCircle size={15} className="spin"/><span>{activeOperation.kind} · 进行中</span><span>查看进度 →</span></button>}
    {!data&&<div className="docker-loading" aria-label="正在读取 Docker" role="status"><span/><span/><span/></div>}
    {data&&showsResources&&<div className="docker-resource-workspace"><div className="docker-resource-toolbar"><div className="docker-resource-tabs" role="group" aria-label="资源类型">{(['containers','images','projects'] as const).map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'selected':''} onClick={()=>{setTab(t);setQuery('');setFilter('all');}}>{t==='containers'?'容器':t==='images'?'镜像':'Compose'}<span>{t==='containers'?data.containers.length:t==='images'?data.images.length:data.projects.length}</span></button>)}</div><button className="button primary compact" disabled={working||!!data.error} onClick={()=>setForm(tab==='containers'?'create':tab==='images'?'pull':'project')}><Plus size={16}/>{tab==='containers'?'创建容器':tab==='images'?'拉取镜像':'导入 Compose'}</button></div>
      <div className="docker-filter-bar"><label className="search"><Search size={15}/><input type="search" aria-label="搜索 Docker 资源" placeholder={tab==='containers'?'搜索名称、镜像或端口…':'搜索名称…'} value={query} onChange={e=>setQuery(e.target.value)}/></label>{tab==='containers'&&<select aria-label="筛选容器状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部状态</option><option value="running">运行中</option><option value="stopped">未运行</option><option value="readonly">外部只读</option></select>}<span className="docker-list-summary">{tab==='containers'?data.containers.filter(c=>c.state==='running').length+' 个运行中':tab==='images'?'镜像可用于创建容器':'统一管理多个服务'}</span></div>
      <section className="docker-results" aria-label="Docker 资源列表" tabIndex={0}><ResourceList data={data} tab={tab} query={query} filter={filter} working={working} control={control} invoke={invoke} showLogs={(name,text)=>setLogs({name,text})} command={c=>{setCommandTarget(c);setCommandId('');}} remove={(name,path,description)=>setRemoving({name,path,description})} create={value=>{if(value)setImage(value);setForm('create');}} importProject={()=>setForm('project')} clear={()=>{setQuery('');setFilter('all');}}/></section>
      <footer className="docker-resource-foot"><span>{data.engine?.kind==='managed'?'本机访问 · 数据持续保留':'外部引擎 · 其他应用的容器只读'}</span><button className="text-button" onClick={()=>setHistory(true)}>查看操作记录{recent.length?' · '+recent.length:''}</button></footer>
    </div>}
    {data&&!showsResources&&<div className="docker-welcome"><Empty title={selectedMode==='managed'?'准备好，再开始你的第一个服务。':'连接后，在这里查看容器。'} description={selectedMode==='managed'?'启用或选择上方的内置引擎，容器和镜像会显示在这里。':'点击上方“连接引擎”，选择这台电脑的 Docker 环境。'}/></div>}
    {history&&<Modal title="Docker 操作记录" close={()=>setHistory(false)}><section className="operation-list" aria-label="Docker 操作记录">{recent.length?recent.map(o=><details key={o.id} open={o.state==='running'||o.state==='failed'}><summary><span>{o.kind}</span><span className={o.state==='failed'?'form-error':''}>{o.state==='running'?'进行中':o.state==='succeeded'?'已完成':'失败'}</span></summary><pre>{o.message||'正在处理…'}</pre></details>):<p className="notice">还没有操作记录。创建、启停和备份的结果会显示在这里。</p>}</section></Modal>}
    {form&&<Modal title={form==='create'?'创建容器':form==='pull'?'拉取镜像':'导入 Compose'} close={()=>{if(!pending)setForm(undefined);}}><form onSubmit={async e=>{e.preventDefault();const fields=new FormData(e.currentTarget);try{if(form==='project')await invoke('projects',{name:fields.get('name'),filePath:projectPath});else if(form==='pull')await invoke('pull',{image});else {
      const ports=String(fields.get('ports')??'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(line=>{const m=line.match(/^(\d+):(\d+)(?:\/(tcp|udp))?$/);if(!m)throw new Error('端口格式应为 8080:80 或 5353:53/udp，每行一条');return {hostPort:Number(m[1]),targetPort:Number(m[2]),protocol:m[3]??'tcp'};});
      await invoke('containers',{name:fields.get('name'),image,memoryMB:Number(fields.get('memory')),cpus:Number(fields.get('cpus')),ports,environment:String(fields.get('environment')??'').split(/\r?\n/).filter(Boolean)});
    }setForm(undefined);}catch(e){setError((e as Error).message);}}}>
      {form!=='pull'&&<label>名称<input name="name" required maxLength={63} placeholder={form==='project'?'我的服务':'my-nginx'}/></label>}
      {form==='project'?<><label>Compose 文件<div className="inline"><input required value={projectPath} onChange={e=>setProjectPath(e.target.value)} placeholder="D:\项目\compose.yaml"/><button type="button" className="button secondary" onClick={()=>void pick('compose',projectPath||undefined).then(result=>{if(result.path)setProjectPath(result.path);})}>选择文件</button></div></label><p className="field-help">保留原文件，DeskLab 单独生成标签与本机端口覆盖配置。暂不支持 build、宿主目录挂载或特权容器。</p></>:<label>镜像<input required value={image} onChange={e=>setImage(e.target.value)} placeholder="nginx:alpine"/></label>}
      {form==='create'&&<><div className="form-grid"><label>内存（MB）<input name="memory" type="number" min={64} max={32768} defaultValue={512} required/></label><label>CPU 核数<input name="cpus" type="number" min={0.1} max={32} step={0.1} defaultValue={1} required/></label></div><label>端口映射<textarea name="ports" rows={3} placeholder={'8080:80\n5353:53/udp'}/></label><p className="field-help">每行“本机端口:容器端口”，默认 TCP，仅绑定 127.0.0.1。端口冲突会报错，不会静默更换。</p><details><summary>环境变量</summary><textarea name="environment" rows={4} placeholder="每行 KEY=value"/><p className="field-help">环境变量交给 Docker，DeskLab 数据库不保存其内容。</p></details></>}
      {error&&<p className="form-error" role="alert">{error}</p>}<footer className="modal-foot"><button type="button" className="button secondary" onClick={()=>setForm(undefined)} disabled={pending}>取消</button><button className="button primary" disabled={pending}>{form==='project'?'校验并导入':form==='pull'?'开始拉取':'创建并启动'}</button></footer>
    </form></Modal>}
    {logs&&<Modal title={`${logs.name} · 最近 200 行日志`} close={()=>setLogs(undefined)}><pre className="task-output">{logs.text||'暂无日志'}</pre></Modal>}
    {commandTarget&&<Modal title={`${commandTarget.name} · 执行命令`} close={()=>setCommandTarget(undefined)}><form onSubmit={e=>{e.preventDefault();void invoke(`containers/${commandTarget.id}/exec`,{command:new FormData(e.currentTarget).get('command')}).then(r=>setCommandId(r.id)).catch(()=>{});}}><label>容器内 Shell 命令<textarea name="command" required rows={3} placeholder="ls -la"/></label><button className="button primary" disabled={working}>执行</button></form><pre className="task-output" role="status">{execution?execution.state==='running'?'命令执行中…':execution.message:'命令在此容器内部执行。'}</pre></Modal>}
    {removing&&<Modal title={`删除 ${removing.name}`} close={()=>setRemoving(undefined)}><p>{removing.description}</p><footer className="modal-foot"><button className="button secondary" onClick={()=>setRemoving(undefined)}>取消</button><button className="button danger" disabled={working} onClick={()=>void invoke(removing.path).then(()=>setRemoving(undefined)).catch(()=>{})}>确认删除</button></footer></Modal>}
    {picker}
  </section>;
}
