import {Box,FileText,Layers,Play,Terminal} from 'lucide-react';
import type {DockerContainer,DockerSnapshot} from '@/shared/docker';
import {Empty} from '../primitives';

export type ResourceTab='containers'|'images'|'projects';
export function ResourceList({data,tab,query,filter,working,control,invoke,showLogs,command,remove,create,importProject,clear}:{data:DockerSnapshot;tab:ResourceTab;query:string;filter:string;working:boolean;control:(c:DockerContainer,verb:string)=>void;invoke:(path:string,body?:unknown)=>Promise<any>;showLogs:(name:string,text:string)=>void;command:(c:DockerContainer)=>void;remove:(name:string,path:string,description:string)=>void;create:(image?:string)=>void;importProject:()=>void;clear:()=>void}) {
  const matches=(...values:string[])=>values.join(' ').toLowerCase().includes(query.trim().toLowerCase());
  const containers=data.containers.filter(c=>matches(c.name,c.image,...c.ports.map(p=>String(p.hostPort)))&&(filter==='all'||(filter==='running'?c.state==='running':filter==='readonly'?!c.owned:c.state!=='running')));
  const images=data.images.filter(i=>matches(i.name,i.id)),projects=data.projects.filter(p=>matches(p.name,p.filePath));
  const total=tab==='containers'?data.containers.length:tab==='images'?data.images.length:data.projects.length;
  const count=tab==='containers'?containers.length:tab==='images'?images.length:projects.length;
  if(!total)return <div className="docker-empty"><div className="docker-empty-symbol" aria-hidden="true">{tab==='projects'?<Layers size={44} strokeWidth={1.2}/>:<Box size={44} strokeWidth={1.2}/>}</div><div><span className="docker-empty-label">{tab==='containers'?'容器工作区':tab==='images'?'镜像仓库':'Compose 项目'}</span><h2>{tab==='containers'?'从一个服务开始。':tab==='images'?'准备你的第一个镜像。':'让多个服务一起运行。'}</h2><p>{tab==='containers'?'运行 Web 服务、数据库与开发工具。在这里查看状态，找到服务的访问入口。':tab==='images'?'拉取已有镜像后，即可创建容器。镜像下载一次，可以反复使用。':'导入 Compose 文件，统一管理服务、端口和命名数据卷。'}</p>{tab==='containers'&&<div className="docker-empty-actions"><button className="button primary" disabled={working||!!data.error} onClick={()=>create()}><Play size={15}/>从镜像开始</button><button className="text-button" disabled={working||!!data.error} onClick={importProject}>导入项目 →</button></div>}<small>{data.engine?.kind==='managed'?'独立存储在这台电脑 · 按需启动引擎':'当前连接外部引擎 · 已有容器保持独立'}</small></div></div>;
  if(!count)return <Empty title="没有匹配的资源" description="换一个名称、镜像或端口试试。"><button className="text-button" onClick={clear}>清除筛选</button></Empty>;
  if(tab==='images')return <div className="data-table-wrap docker-image-table"><table className="data-table"><thead><tr><th>镜像 / 标识</th><th>大小</th><th>操作</th></tr></thead><tbody>{images.map((item,i)=><tr key={item.id+':'+i}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.size}</td><td><button className="text-button" disabled={working||item.name.startsWith('<none>')} onClick={()=>create(item.name)}>创建容器</button></td></tr>)}</tbody></table></div>;
  if(tab==='projects')return <div className="container-list docker-project-list">{projects.map(p=><article className="container-row" key={p.id}><span className="container-symbol"><Layers size={20}/></span><div className="container-copy"><h3>{p.name}</h3><p>{p.filePath}</p><small>{p.composeName}</small></div><div className="container-actions">{(['up','stop','down'] as const).map(verb=><button className="button secondary compact" key={verb} disabled={working} onClick={()=>void invoke(`projects/${p.id}/${verb}`).catch(()=>{})}>{verb==='up'?'启动 / 更新':verb==='stop'?'停止':'移除容器'}</button>)}<button className="text-button" disabled={working} onClick={()=>remove(p.name,`projects/${p.id}/delete`,'删除项目记录前需先移除容器。已有数据卷保留在 Docker 中。')}>删除记录</button></div></article>)}</div>;
  return <div className="container-list docker-container-list">{containers.map(c=><article className="container-row" key={c.id}><span className={`container-symbol ${c.state==='running'?'is-running':''}`}><Box size={20}/></span><div className="container-copy"><h3>{c.name}</h3><p>{c.image}</p><small>{c.owned?c.projectId?'Compose 项目':'DeskLab 管理':'外部容器 · 只读'}</small><div className="port-chips">{c.ports.map((p,i)=><code key={i}>{p.hostAddress}:{p.hostPort} → {p.targetPort}/{p.protocol}</code>)}</div></div><span className={`status ${c.state==='running'?'running':'stopped'}`}><span/>{c.state==='running'?'运行中':c.state==='exited'?'已停止':c.state==='engine-stopped'?'引擎已停止':c.state}</span>{c.owned&&<div className="container-actions">{!c.projectId&&<><button className="button secondary compact" disabled={working} onClick={()=>control(c,c.state==='running'?'stop':'start')}>{c.state==='running'?'停止':'启动'}</button><button className="button secondary compact" disabled={working||c.state!=='running'} onClick={()=>control(c,'restart')}>重启</button></>}<button className="icon-button" aria-label={`查看 ${c.name} 日志`} disabled={working} onClick={()=>void invoke(`containers/${c.id}/logs`).then(r=>showLogs(c.name,r.text)).catch(()=>{})}><FileText size={17}/></button><button className="icon-button" aria-label={`在 ${c.name} 执行命令`} disabled={working||c.state!=='running'} onClick={()=>command(c)}><Terminal size={17}/></button>{!c.projectId&&<button className="text-button" disabled={working||c.state==='running'} onClick={()=>remove(c.name,`containers/${c.id}/delete`,'删除已停止的容器。命名数据卷不会被删除。')}>删除</button>}</div>}{!c.owned&&<div className="container-actions docker-readonly-space" aria-hidden="true"/>}</article>)}</div>;
}
